name: CDKTF Deployment

on:
  push:
    branches:
      - production
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2


      - name: Install Python dependencies & CDKTF CLI
        run: |
          cd cdktf
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install --global cdktf-cli

      - name: Configure AWS credentials and deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          cd cdktf
          cdktf deploy --auto-approve
